# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30f217ac74a7d48c440ffa8ad8844f6d7440d252370e17281bee2f527ad1e5916e3a53c0b04c06d20efcbc05706b866f431b2601d2fb2a5a5655cc241ae672d4

test:
  secret_key_base: 6f21c2141f92104c710e49fd873f8b4080d5152e194ce9ce5df8886f6a49320c098979d1ffcae5d025b22bc24419b20f537c6b3810ed725c7da5c49ff0a2876c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
